#include <stdbool.h>
#include <stdlib.h>

#include "../event_handler/events.h"
#include "supR5EsteiraMesa_GiratoriaFuradeira.h"

// Supervisor specific instances
// alphabet create
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_a1_evt0;
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_a2_evt1;
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_b2_evt2;
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_b0_evt3;
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_b1_evt4;
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_a0_evt5;

// Alphabet init
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_a1_evt0 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_a2_evt1};
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_a2_evt1 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_b2_evt2};
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_b2_evt2 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_b0_evt3};
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_b0_evt3 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_b1_evt4};
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_b1_evt4 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_a0_evt5};
const Alphabet supR5EsteiraMesa_GiratoriaFuradeira_a0_evt5 = {&a0, NULL};

// states create
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1;
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0;
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1;

// transitions create and init
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0_t0 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0_t1 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1_t0 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1_t1 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t1 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t2 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t2 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0_t0 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0_t1 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1_t0 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1_t1 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t1 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t2 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t2 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0_t0 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1_t0 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0_t1 = {&a2, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0_t0 = {&a0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0_t1 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t0 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t1 = {&a0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t2 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0_t1 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t2 = {&a1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0_t0 = {&a0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0_t1 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t0 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t1 = {&a0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t2 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0_t1 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t2;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t2};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t2 = {&b1, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0_t0 = {&a0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1_t0 = {&a0, &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0, NULL};

const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1_t0;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1_t1;
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1_t0 = {&b0, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1_t1};
const Transition supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1_t1 = {&b2, &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0, NULL};


// states init
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0 = {false, SUP_DEBUG_STR("S2_S0_S0_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1 = {false, SUP_DEBUG_STR("S2_S0_S0_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S0_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0 = {false, SUP_DEBUG_STR("S2_S0_S1_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1 = {false, SUP_DEBUG_STR("S2_S0_S1_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S0_S1_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0 = {false, SUP_DEBUG_STR("S2_S1_S0_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1 = {false, SUP_DEBUG_STR("S2_S1_S0_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S0_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0 = {false, SUP_DEBUG_STR("S2_S1_S1_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1 = {false, SUP_DEBUG_STR("S2_S1_S1_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S2_S1_S1_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0 = {false, SUP_DEBUG_STR("S3_S0_S0_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1 = {false, SUP_DEBUG_STR("S3_S0_S0_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S0_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0 = {false, SUP_DEBUG_STR("S3_S0_S1_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1 = {false, SUP_DEBUG_STR("S3_S0_S1_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S3_S0_S1_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0 = {true, SUP_DEBUG_STR("S4_S0_S0_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1 = {false, SUP_DEBUG_STR("S4_S0_S0_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0 = {false, SUP_DEBUG_STR("S4_S0_S1_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1 = {false, SUP_DEBUG_STR("S4_S0_S1_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S1_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0 = {false, SUP_DEBUG_STR("S4_S1_S0_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1 = {false, SUP_DEBUG_STR("S4_S1_S0_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S0_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0 = {false, SUP_DEBUG_STR("S4_S1_S1_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1 = {false, SUP_DEBUG_STR("S4_S1_S1_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S4_S1_S1_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0 = {false, SUP_DEBUG_STR("S5_S0_S0_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1 = {false, SUP_DEBUG_STR("S5_S0_S0_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S0_S1_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0 = {false, SUP_DEBUG_STR("S5_S0_S1_S0"), &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S0_t0};
const State supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1 = {false, SUP_DEBUG_STR("S5_S0_S1_S1"), &supR5EsteiraMesa_GiratoriaFuradeira_S5_S0_S1_S1_t0};

// Supervisor create
Supervisor supR5EsteiraMesa_GiratoriaFuradeira = {&supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0, &supR5EsteiraMesa_GiratoriaFuradeira_S4_S0_S0_S0, NULL,  &supR5EsteiraMesa_GiratoriaFuradeira_a1_evt0, "supR5EsteiraMesa_GiratoriaFuradeira"};
