#include <stdbool.h>
#include <stdlib.h>

#include "../event_handler/events.h"
#include "supR8EsteiraMesa_GiratoriaFuradeiraTeste.h"

// Supervisor specific instances
// alphabet create
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a3_evt0;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a2_evt1;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a1_evt2;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b3_evt3;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b2_evt4;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b0_evt5;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b1_evt6;
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a0_evt7;

// Alphabet init
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a3_evt0 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_a2_evt1};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a2_evt1 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_a1_evt2};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a1_evt2 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_b3_evt3};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b3_evt3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_b2_evt4};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b2_evt4 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_b0_evt5};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b0_evt5 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_b1_evt6};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_b1_evt6 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_a0_evt7};
const Alphabet supR8EsteiraMesa_GiratoriaFuradeiraTeste_a0_evt7 = {&a0, NULL};

// states create
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0;
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1;

// transitions create and init
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t0 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t1 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t2 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t0 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t1 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t0 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t1 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t0 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t1 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t1 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t2 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t1 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t2 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t1 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t2 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t3 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t1 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t0 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t1 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t2 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t0 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t0 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t0 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t1 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t1 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t2 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t3 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t1 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t2 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t1 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t2 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t3 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t1 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t2 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t1 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t2 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t1 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t2 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t1 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t1 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t2 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t1 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t2 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t1 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t2 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t0 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t1 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t3 = {&a1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t2 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t3 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t3 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t3 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t0 = {&a0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t1 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t0 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t1 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t2 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t3 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t0 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t1 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t2 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t3 = {&a2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t0 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t1 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t3 = {&a3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1, NULL};

const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t0;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t1;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t2;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t3;
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t0 = {&b1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t1};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t1 = {&b0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t2};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t2 = {&b2, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t3};
const Transition supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t3 = {&b3, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0, NULL};


// states init
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0 = {true, SUP_DEBUG_STR("S0_S0_S0_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1 = {false, SUP_DEBUG_STR("S0_S0_S0_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0 = {false, SUP_DEBUG_STR("S0_S0_S0_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1 = {false, SUP_DEBUG_STR("S0_S0_S0_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0 = {false, SUP_DEBUG_STR("S0_S0_S1_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1 = {false, SUP_DEBUG_STR("S0_S0_S1_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0 = {false, SUP_DEBUG_STR("S0_S0_S1_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1 = {false, SUP_DEBUG_STR("S0_S0_S1_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S1_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0 = {false, SUP_DEBUG_STR("S0_S1_S0_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1 = {false, SUP_DEBUG_STR("S0_S1_S0_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0 = {false, SUP_DEBUG_STR("S0_S1_S0_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1 = {false, SUP_DEBUG_STR("S0_S1_S0_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S0_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0 = {false, SUP_DEBUG_STR("S0_S1_S1_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1 = {false, SUP_DEBUG_STR("S0_S1_S1_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0 = {false, SUP_DEBUG_STR("S0_S1_S1_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1 = {false, SUP_DEBUG_STR("S0_S1_S1_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S1_S1_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0 = {false, SUP_DEBUG_STR("S1_S0_S0_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1 = {false, SUP_DEBUG_STR("S1_S0_S0_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0 = {false, SUP_DEBUG_STR("S1_S0_S0_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1 = {false, SUP_DEBUG_STR("S1_S0_S0_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S0_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0 = {false, SUP_DEBUG_STR("S1_S0_S1_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1 = {false, SUP_DEBUG_STR("S1_S0_S1_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0 = {false, SUP_DEBUG_STR("S1_S0_S1_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1 = {false, SUP_DEBUG_STR("S1_S0_S1_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S0_S1_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0 = {false, SUP_DEBUG_STR("S1_S1_S0_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1 = {false, SUP_DEBUG_STR("S1_S1_S0_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0 = {false, SUP_DEBUG_STR("S1_S1_S0_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1 = {false, SUP_DEBUG_STR("S1_S1_S0_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S0_S1_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0 = {false, SUP_DEBUG_STR("S1_S1_S1_S0_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1 = {false, SUP_DEBUG_STR("S1_S1_S1_S0_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S0_S1_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0 = {false, SUP_DEBUG_STR("S1_S1_S1_S1_S0"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S0_t0};
const State supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1 = {false, SUP_DEBUG_STR("S1_S1_S1_S1_S1"), &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S1_S1_S1_S1_S1_t0};

// Supervisor create
Supervisor supR8EsteiraMesa_GiratoriaFuradeiraTeste = {&supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0, &supR8EsteiraMesa_GiratoriaFuradeiraTeste_S0_S0_S0_S0_S0, NULL,  &supR8EsteiraMesa_GiratoriaFuradeiraTeste_a3_evt0, "supR8EsteiraMesa_GiratoriaFuradeiraTeste"};
