#include <stdbool.h>
#include <stdlib.h>

#include "../event_handler/events.h"
#include "supR6Mesa_GiratoriaFuradeiraTeste.h"

// Supervisor specific instances
// alphabet create
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_a2_evt0;
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_a3_evt1;
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_b3_evt2;
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_b2_evt3;
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_b0_evt4;
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_a0_evt5;

// Alphabet init
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_a2_evt0 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_a3_evt1};
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_a3_evt1 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_b3_evt2};
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_b3_evt2 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_b2_evt3};
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_b2_evt3 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_b0_evt4};
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_b0_evt4 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_a0_evt5};
const Alphabet supR6Mesa_GiratoriaFuradeiraTeste_a0_evt5 = {&a0, NULL};

// states create
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1;
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0;
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1;

// transitions create and init
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0_t0 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0_t1 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1_t0 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1_t1 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0_t0 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0_t1 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1_t0 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1_t1 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t1 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t2 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t2 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t1 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t2 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t2 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0_t0 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1_t0 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0_t1 = {&a3, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0_t0 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0_t1 = {&a0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t0 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t1 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t2 = {&a0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0_t0 = {&a0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0_t1 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t0 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t1 = {&a0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t2 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0_t1 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t2 = {&a2, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0_t1 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t2;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t2};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t2 = {&b2, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0_t0 = {&a0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1_t0 = {&a0, &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0, NULL};

const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1_t0;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1_t1;
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1_t0 = {&b0, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1_t1};
const Transition supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1_t1 = {&b3, &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0, NULL};


// states init
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0 = {false, SUP_DEBUG_STR("S2_S0_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1 = {false, SUP_DEBUG_STR("S2_S0_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0 = {false, SUP_DEBUG_STR("S2_S0_S1_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1 = {false, SUP_DEBUG_STR("S2_S0_S1_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S0_S1_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0 = {false, SUP_DEBUG_STR("S2_S1_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1 = {false, SUP_DEBUG_STR("S2_S1_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0 = {false, SUP_DEBUG_STR("S2_S1_S1_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1 = {false, SUP_DEBUG_STR("S2_S1_S1_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S2_S1_S1_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0 = {false, SUP_DEBUG_STR("S3_S0_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1 = {false, SUP_DEBUG_STR("S3_S0_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S3_S0_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0 = {false, SUP_DEBUG_STR("S3_S1_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1 = {false, SUP_DEBUG_STR("S3_S1_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S3_S1_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0 = {true, SUP_DEBUG_STR("S4_S0_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1 = {false, SUP_DEBUG_STR("S4_S0_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0 = {false, SUP_DEBUG_STR("S4_S0_S1_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1 = {false, SUP_DEBUG_STR("S4_S0_S1_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S1_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0 = {false, SUP_DEBUG_STR("S4_S1_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1 = {false, SUP_DEBUG_STR("S4_S1_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0 = {false, SUP_DEBUG_STR("S4_S1_S1_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1 = {false, SUP_DEBUG_STR("S4_S1_S1_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S4_S1_S1_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0 = {false, SUP_DEBUG_STR("S5_S0_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1 = {false, SUP_DEBUG_STR("S5_S0_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S5_S0_S0_S1_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0 = {false, SUP_DEBUG_STR("S5_S1_S0_S0"), &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S0_t0};
const State supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1 = {false, SUP_DEBUG_STR("S5_S1_S0_S1"), &supR6Mesa_GiratoriaFuradeiraTeste_S5_S1_S0_S1_t0};

// Supervisor create
Supervisor supR6Mesa_GiratoriaFuradeiraTeste = {&supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0, &supR6Mesa_GiratoriaFuradeiraTeste_S4_S0_S0_S0, NULL,  &supR6Mesa_GiratoriaFuradeiraTeste_a2_evt0, "supR6Mesa_GiratoriaFuradeiraTeste"};
