from .Base import Event, EventKind, State, Supervisor
from .events import Events, get_event_by_id
from .logger import log_error, log_state
from .supervisors import supR0EsteiraSensor,supEsteiraMesa_GiratoriaR1,supR2Mesa_GiratoriaFuradeira,supR3Mesa_GiratoriaTeste,supR4Mesa_GiratoriaRobo,supR5EsteiraMesa_GiratoriaFuradeira,supR6Mesa_GiratoriaFuradeiraTeste,supR7Mesa_GiratoriaTesteRobo,supR8EsteiraMesa_GiratoriaFuradeiraTeste
supervisors_list = [supR0EsteiraSensor,supEsteiraMesa_GiratoriaR1,supR2Mesa_GiratoriaFuradeira,supR3Mesa_GiratoriaTeste,supR4Mesa_GiratoriaRobo,supR5EsteiraMesa_GiratoriaFuradeira,supR6Mesa_GiratoriaFuradeiraTeste,supR7Mesa_GiratoriaTesteRobo,supR8EsteiraMesa_GiratoriaFuradeiraTeste]
# import trigger_event after supervisor_list for avoid circular import
from .event_handler import trigger_event
